[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "piradiosdr"
authors = [{name = "Sundeep Ranagn", email = "srangan@nyu.edu"}]
dynamic = ["version 0", "Software and instructions for the Pi-Radio SDR"]
